services:
  db:
    image: mysql:8.0
    container_name: neuroflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: neuroflow_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # O MySQL no Docker roda automaticamente arquivos .sql contidos nessa pasta ao inicializar
      - ./backend/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - neuroflow-net

  backend:
    build:
      context: ./backend
    container_name: neuroflow-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=neuroflow_db
      - JWT_SECRET=sua_chave_jwt_secreta_e_segura
      - TOKEN_EXPIRATION=1h
      - REFRESH_TOKEN_SECRET=sua_chave_refresh_secreta_e_segura
      - REFRESH_TOKEN_EXPIRATION=30d
      - RESET_TOKEN_EXPIRATION_MINUTES=5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - neuroflow-net

networks:
  neuroflow-net:

volumes:
  mysql_data:
  
